### ISSUE TITLE
create webhook.yaml

### ISSUE THREAD

**Issue by hupiper** [mvazquezc/code-to-prod-demo#1]
oc -n reversewords-ci create -f webhook.yaml
triggertemplate.triggers.tekton.dev/reverseword-build-triggertemplate created
Error from server (BadRequest): error when creating "webhook.yaml": admission webhook "validation.webhook.triggers.tekton.dev" denied the request: validation failed: missing field(s): spec.triggers[0].bindings[0].Value

Currently the name is being set - looks like it need a value too. I'm not sure which tt value to use.

**Comment by hupiper** [comment]
It looks like the webhook event listener should be something like this:

```
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: reversewords-webhook
spec:
  serviceAccountName: reversewords-pipeline
  triggers:
    - name: git-reversewords-trigger
      interceptors:
        - github:
            secretRef:
              secretName: webhook-secret
              secretKey: secret
            eventTypes:
              - push
      bindings:
        - ref: github-triggerbinding
      template:
        ref: reverseword-build-triggertemplate
```
